services:
  lexor-db:
    image: mcr.microsoft.com/mssql/server:2022-CU24-ubuntu-22.04
    container_name: lexor-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DB_SA_PASSWORD}
    ports:
      - "1435:1433"
    expose:
      - "1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  lexor-rabbitmq:
    image: rabbitmq:3-management
    container_name: lexor-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"     # AMQP — aplikacija se spaja ovdje
      - "15672:15672"   # Management UI — http://localhost:15672

volumes:
  sqlserver_data:
