services:
  lexor-db:
    image: mcr.microsoft.com/mssql/server:2022-CU24-ubuntu-22.04
    container_name: lexor-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DB_SA_PASSWORD}
    ports:
      - "1435:1433"
    expose:
      - "1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
