services:
  lexor-db:
    image: mcr.microsoft.com/mssql/server:2022-CU24-ubuntu-22.04
    container_name: lexor-db
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${DB_SA_PASSWORD}
    ports:
      - "1435:1433"
    expose:
      - "1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  lexor-api:
    build:
      context: .
      dockerfile: Lexor.WebAPI/Dockerfile
    container_name: lexor-api
    depends_on:
      - lexor-db
      - lexor-rabbitmq
    env_file:
      - ./Lexor.WebAPI/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=lexor-db,1433;Database=230022;User Id=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True;"
      RabbitMQ__ConnectionString: "host=lexor-rabbitmq;username=admin;password=admin"
    ports:
      - "5000:8080"
    restart: unless-stopped

  lexor-worker:
    build:
      context: .
      dockerfile: Lexor.Subscriber/Dockerfile
    container_name: lexor-worker
    depends_on:
      - lexor-db
      - lexor-rabbitmq
    env_file:
      - ./Lexor.Subscriber/.env
    environment:
      ConnectionStrings__DefaultConnection: "Server=lexor-db,1433;Database=230022;User Id=sa;Password=${DB_SA_PASSWORD};TrustServerCertificate=True;"
      RabbitMQ__ConnectionString: "host=lexor-rabbitmq;username=admin;password=admin"
    restart: unless-stopped

  lexor-rabbitmq:
    image: rabbitmq:3-management
    container_name: lexor-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  sqlserver_data:
